### Register User
POST http://localhost:8080/change-password
Content-Type: application/json



> {% client.global.set("auth-token", response.body.access_token);  %}

### Query the Demo endpoint
GET http://localhost:8080/change-password
Authorization: Bearer {{auth-token}}


### Change the password
PATCH http://localhost:8080/change-password
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "currentPassword": "password",
  "newPassword": "newPassword",
  "confirmationPassword":  "newPassword"
}

### Login again and update the token
POST http://localhost:8080/change-password
Content-Type: application/json

{
  "email":  "alibou@mail.com",
  "password": "newPassword"
}

> {% client.global.set("new-auth-token", response.body.access_token);  %}


### Query the Demo endpoint after password change
GET http://localhost:8080/change-password
Authorization: Bearer {{new-auth-token}}